name: Run test

on:
  schedule:
    - cron:  '* */ * * *'
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Run test
        run: mvn clean test -Dtestng.dtd.http=true